[tasks.rust_clean]
script = [
  """
    cd rust-lib
    cargo clean

    cd ../../shared-lib
    cargo clean

    CACHE_FILE=lib-infra/.cache
    if [ -d "$CACHE_FILE" ]; then
      echo "Remove $CACHE_FILE"
      rm -rf $CACHE_FILE
    fi
  """,
]
script_runner = "@shell"

[tasks.rust_clean.windows]
script = [
  """
    cd rust-lib
    cargo clean

    cd ../../shared-lib
    rmdir /s/q "lib-infra/.cache"
  """,
]
script_runner = "@duckscript"