
proto_rust_file_input_dir = ["src/entities", "src/event_map.rs", "src/dart_notification.rs"]
proto_file_output_dir = "resources/proto"
protobuf_crate_output_dir = "src/protobuf"
event_files = ["src/event_map.rs"]